config/routes.rb
Rails.application.routes.draw do

  # アドミン側ルーティング
  get 'admin' => 'admin/home#show'
  namespace :admin do
    resources :customers

    resources :employees do
      member do
        get :edit_customers
        patch :update_customers
      end
    end
  end

  # 一般側ルーティング
  get 'home' => 'home/home#show'
  namespace :home do
    resources :customers do
      resources :visit_histories
    end
  end

  # デバイス設定
  devise_for :employees,
    controllers: {
      registrations: 'employees/registrations',
    }

  # root画面
  root 'welcome#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  # if ENV['ADMIN_REGISTRATION'].to_i == 1
    DEVISE_OPTIONS = [
        :database_authenticatable,
        :registerable,
        :recoverable,
        :rememberable,
        :trackable,
        :validatable
    ]
  # else
  #   DEVISE_OPTIONS = [
  #       :database_authenticatable,
  #       # :registerable,
  #       :recoverable,
  #       :rememberable,
  #       :trackable,
  #       :validatable
  #   ]
  # end
  devise(* DEVISE_OPTIONS)

  validates :name, presence: true
  validates :email, presence: true

  has_many :customers_employees
  has_many :customers, through: :customers_employees

end

app/controllers/admin/employees_controller.rb
# 管理側担当者管理

class Admin::EmployeesController < Admin::AdminAuthorizedController

  before_action :set_employee, only: [:show, :edit, :update, :destroy, :edit_customers, :update_customers]

  before_action do
    if action_name == 'index'
      add_breadcrumb '社員管理'
    else
      add_breadcrumb '社員管理', admin_employees_path
    end
  end

  def index
    @employees = Employee.page(params[:page]).all
  end

  def edit
    add_breadcrumb @employee.name, admin_employee_path(@employee)
    add_breadcrumb '更新'
  end

  def show
    add_breadcrumb @employee.name
  end

  def update
    add_breadcrumb @employee.name

    if @employee.update(employee_params)
      redirect_to [:admin, @employee], notice: '更新しました。'
    else
      render :edit
    end
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to [:admin, @employee], notice: '作成しました。'
    else
      render :new
    end

  end

  def destroy
    @employee.destroy
    redirect_to admin_employees_url, notice: '削除しました。'
  end

  def edit_customers
    add_breadcrumb "#{@employee.name}さんの担当顧客変更"
    @customers = Customer.all
  end

  def update_customers
    @employee.customers = Customer.where(id: params[:customer_ids]).all
    @employee.save!
    redirect_to [:admin, @employee], notice: '更新しました。'
  end

  private

  def set_employee
    @employee = Employee.includes(:customers).find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:name, :email, :admin, :password, :password_confirmation)
  end
end

app/controllers/employees/registrations_controller.rb
# https://github.com/plataformatec/devise/wiki/How-To:-Redirect-to-a-specific-page-on-successful-sign-up-%28registration%29

#
class Employees::RegistrationsController < Devise::RegistrationsController
  prepend_before_filter :require_no_authentication, only: [ :new, :create, :cancel ]
  prepend_before_filter :authenticate_scope!, only: [:edit, :update, :destroy]

  before_action({only: [:new, :create]}) do
    raise if ENV['ADMIN_REGISTRATION'].to_i != 1
  end

  # GET /resource/sign_up
  def new
    build_resource({})
    @validatable = devise_mapping.validatable?
    if @validatable
      @minimum_password_length = resource_class.password_length.min
    end
    respond_with self.resource
  end

  # POST /resource
  def create

    build_resource(sign_up_params)

    resource.admin = true # adminに設定

    resource_saved = resource.save
    yield resource if block_given?
    if resource_saved
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      @validatable = devise_mapping.validatable?
      if @validatable
        @minimum_password_length = resource_class.password_length.min
      end
      respond_with resource
    end
  end

  # GET /resource/edit
  def edit
    render :edit
  end

  # PUT /resource
  # We need to use a copy of the resource because we don't want to change
  # the current user in place.
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      if is_flashing_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
            :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, bypass: true
      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # DELETE /resource
  def destroy
    resource.destroy
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    expire_data_after_sign_in!
    redirect_to new_registration_path(resource_name)
  end

  protected

  def update_needs_confirmation?(resource, previous)
    resource.respond_to?(:pending_reconfirmation?) &&
        resource.pending_reconfirmation? &&
        previous != resource.unconfirmed_email
  end

  # By default we want to require a password checks on update.
  # You can overwrite this method in your own RegistrationsController.
  def update_resource(resource, params)
    resource.update_with_password(params)
  end

  # Build a devise resource passing in the session. Useful to move
  # temporary session data to the newly created user.
  def build_resource(hash=nil)
    self.resource = resource_class.new_with_session(hash || {}, session)
  end

  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  # The path used after sign up. You need to overwrite this method
  # in your own RegistrationsController.
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  # The path used after sign up for inactive accounts. You need to overwrite
  # this method in your own RegistrationsController.
  def after_inactive_sign_up_path_for(resource)
    scope = Devise::Mapping.find_scope!(resource)
    router_name = Devise.mappings[scope].router_name
    context = router_name ? send(router_name) : self
    context.respond_to?(:root_path) ? context.root_path : "/"
  end

  # The default url to be used after updating a resource. You need to overwrite
  # this method in your own RegistrationsController.
  def after_update_path_for(resource)
    signed_in_root_path(resource)
  end

  # Authenticates the current scope and gets the current resource from the session.
  def authenticate_scope!
    send(:"authenticate_#{resource_name}!", force: true)
    self.resource = send(:"current_#{resource_name}")
  end

  # def sign_up_params
  #   devise_parameter_sanitizer.sanitize(:sign_up)
  # end

  def sign_up_params
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    super
  end

  def account_update_params
    # http://www.jacopretorius.net/2014/03/adding-custom-fields-to-your-devise-user-model-in-rails-4.html
    params.require(:employee).permit(:name, :email, :email, :password, :password_confirmation, :current_password)
  end
end

app/views/admin/employees/_form.html.erb
<%= bootstrap_form_for([:admin, @employee]) do |f| %>
  <% if @employee.errors.any? %>
    <div class="alert alert-danger">
      <p><%= @employee.errors.count %>件のエラーが有ります。</p>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name %>
  <%= f.email_field :email %>
  <%= f.check_box :admin %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>

<% end %>

app/views/admin/employees/edit.html.erb
<h1>顧客変更</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @employee] %> |
<%= link_to 'Back', admin_employees_path %>

app/views/admin/employees/edit_customers.html.erb
<h2><%= @employee.name %>さんの担当顧客変更</h2>

<%= form_tag(update_customers_admin_employee_path(@employee), method: :patch) do %>
  <% @customers.each do |customer| %>
    <div>
      <label>
        <%= check_box_tag 'customer_ids[]', customer.id, @employee.customers.all.find{|c| c.id == customer.id} %>
        <%= customer.name %>
      </label>
    </div>
  <% end %>

  <%= submit_tag '更新', class: 'btn btn-info' %>
<% end %>

app/views/admin/employees/index.html.erb
<h1>社員管理</h1>


<div>
  <%= paginate @employees %>
</div>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>名前</th>
    <th>EMail</th>
    <th>管理者</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @employees.each do |employee| %>
    <tr>
      <td><%= link_to employee.name, [:admin, employee] %></td>
      <td><%= employee.email %></td>
      <td><%= employee.admin ? 'Yes' : 'No' %></td>
      <td><%= link_to '編集', edit_admin_employee_path(employee) %></td>
      <td><%= link_to '削除', [:admin, employee], method: :delete, data: { confirm: '削除してよろしいですか?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<div>
  <%= paginate @employees %>
</div>

<br>

<%= link_to '社員新規作成', new_admin_employee_path, class: 'btn btn-info' %>

app/views/admin/employees/new.html.erb
<h1>社員新規作成</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_employees_path %>

app/views/admin/employees/show.html.erb
<p>
  <strong>名前:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>管理者？:</strong>
  <%= @employee.admin ? 'Yes' : 'No' %>
</p>

<%= link_to 'Edit', edit_admin_employee_path(@employee) %> |
<%= link_to 'Back', admin_employees_path %>

<hr/>

<h3>担当顧客</h3>

<table class="table table-bordered">
  <tr>
    <th>
      顧客名
    </th>
  </tr>

  <% @employee.customers.each do |customer| %>
  <tr>
    <td>
      <%= customer.name %>
    </td>
  </tr>
<% end %>
</table>

<div>
  <%= link_to '担当顧客を変更', edit_customers_admin_employee_path(@employee), class: 'btn btn-info' %>
</div>