config/routes.rb
Rails.application.routes.draw do

  # アドミン側ルーティング
  get 'admin' => 'admin/home#show'
  namespace :admin do
    resources :customers

    resources :employees do
      member do
        get :edit_customers
        patch :update_customers
      end
    end
  end

  # 一般側ルーティング
  get 'home' => 'home/home#show'
  namespace :home do
    resources :customers do
      resources :visit_histories
    end
  end

  # デバイス設定
  devise_for :employees,
    controllers: {
      registrations: 'employees/registrations',
    }

  # root画面
  root 'welcome#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  validates :name, presence: true, length: {maximum: 255}
  validates :address, presence: true, length: {maximum: 255}
  validates :tel, presence: true, length: {maximum: 20}

  has_many :visit_histories

  has_many :customers_employees
  has_many :employees, through: :customers_employees
end

app/controllers/admin/customers_controller.rb
# 管理側顧客管理

class Admin::CustomersController < Admin::AdminAuthorizedController

  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  before_action do
    if action_name == 'index'
      add_breadcrumb '顧客管理'
    else
      add_breadcrumb '顧客管理', admin_customers_path
    end
  end

  def index
    @customers = Customer.page(params[:page]).all
  end

  def show
    add_breadcrumb @customer.name
  end

  def new
    @customer = Customer.new
  end

  def edit
    add_breadcrumb @customer.name, admin_customer_path(@customer)
    add_breadcrumb '更新'
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to admin_customers_path, notice: '作成しました。'
    else
      render :new
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to admin_customers_path, notice: '更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @customer.destroy
    redirect_to admin_customers_url, notice: '削除しました。'
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:name, :address, :tel, :memo)
  end
end

app/controllers/customers_controller.rb
class CustomersController < AuthorizedController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = current_employee.customers.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def edit
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      @customer.employees << current_employee

      redirect_to @customer, notice: '作成しました。'
    else
      render :new
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: '更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @customer.destroy
    redirect_to customers_url, notice: '削除しました。'
  end

  private

    def set_customer
      @customer = current_employee.customers.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name, :address, :tel, :memo)
    end
end

app/controllers/home/customers_controller.rb
# 顧客管理コントローラー

class Home::CustomersController < Home::AuthorizedController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  before_action do
    if action_name == 'index'
      add_breadcrumb '担当顧客管理'
    else
      add_breadcrumb '担当顧客管理', home_customers_path
    end
  end

  def index
    @customers = current_employee.customers.all
  end

  def show
    add_breadcrumb @customer.name
  end

  def new
    add_breadcrumb '新規作成'
    @customer = Customer.new
  end

  def edit
    add_breadcrumb @customer.name
    add_breadcrumb '更新'
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      @customer.employees << current_employee

      redirect_to [:home, @customer], notice: '作成しました。'
    else
      render :new
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to [:home, @customer], notice: '更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @customer.destroy
    redirect_to home_customers_url, notice: '削除しました。'
  end

  private

    def set_customer
      @customer = current_employee.customers.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name, :address, :tel, :memo)
    end
end

app/views/admin/customers/_form.html.erb
<%= bootstrap_form_for([:admin, @customer]) do |f| %>
  <% if @customer.errors.any? %>
    <div class="alert alert-danger">
      <p><%= @customer.errors.count %>件のエラーが有ります。</p>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name %>
  <%= f.text_area :address %>
  <%= f.text_field :tel %>
  <%= f.text_area :memo %>

  <%= f.submit %>

<% end %>

app/views/admin/customers/edit.html.erb
<h1>顧客変更</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @customer] %> |
<%= link_to 'Back', admin_customers_path %>

app/views/admin/customers/index.html.erb
<h1>顧客管理</h1>

<div>
  <%= paginate @customers %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>顧客名</th>
      <th>住所</th>
      <th>Tel</th>
      <th>メモ</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.name, [:admin, customer] %></td>
        <td><%= customer.address %></td>
        <td><%= customer.tel %></td>
        <td><%= customer.memo %></td>
        <td><%= link_to '編集', edit_admin_customer_path(customer) %></td>
        <td><%= link_to '削除', [:admin, customer], method: :delete, data: { confirm: '削除してよろしいですか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= paginate @customers %>
</div>

<br>

<%= link_to '顧客新規作成', new_admin_customer_path, class: 'btn btn-info' %>

app/views/admin/customers/new.html.erb
<h1>顧客新規作成</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_customers_path %>

app/views/admin/customers/show.html.erb
<h2><%= @customer.name %></h2>

<p>
  <strong>住所:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @customer.tel %>
</p>

<p>
  <strong>メモ:</strong>
  <%= @customer.memo %>
</p>

<%= link_to 'Edit', edit_admin_customer_path(@customer) %> |
<%= link_to 'Back', admin_customers_path %>

<hr>

<div>
  <div>
    <div class="pull-left" style="font-size: 28px;">訪問履歴</div>
  </div>

  <% if @customer.visit_histories.exists? %>

    <table class="table table-bordered">
      <thead>
      <tr>
        <th>訪問日時</th>
        <th>メモ</th>
        <th>次回訪問予定</th>
        <th>訪問者</th>
      </tr>
      </thead>

      <tbody>
      <% @customer.visit_histories.each do |visit_history| %>
        <tr>
          <td><%= time_str(visit_history.visited_at) %></td>
          <td><%= visit_history.memo %></td>
          <td><%= visit_history.next_visit_at %></td>
          <td><%= visit_history.visited_employee.name %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>
</div>