config/routes.rb
Rails.application.routes.draw do

  # アドミン側ルーティング
  get 'admin' => 'admin/home#show'
  namespace :admin do
    resources :customers

    resources :employees do
      member do
        get :edit_customers
        patch :update_customers
      end
    end
  end

  # 一般側ルーティング
  get 'home' => 'home/home#show'
  namespace :home do
    resources :customers do
      resources :visit_histories
    end
  end

  # デバイス設定
  devise_for :employees,
    controllers: {
      registrations: 'employees/registrations',
    }

  # root画面
  root 'welcome#index'

end

app/models/visit_history.rb
class VisitHistory < ActiveRecord::Base

  belongs_to :customer
  belongs_to :visited_employee, class_name: Employee.name

end

app/controllers/admin/visit_histories_controller.rb
# 管理側 訪問管理
class Admin::VisitHistoriesController < Admin::AdminAuthorizedController

  before_action :set_customer
  before_action :set_visit_history, only: [:edit, :update, :destroy]

  def edit
  end

  def update
    if @visit_history.update(visit_history_params)
      redirect_to admin_customer_path(@customer), notice: '訪問概要を更新しました。'
      # redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @visit_history.destroy
    redirect_to visit_histories_url, notice: 'Visit history was successfully destroyed.'
  end

  private

  def set_customer
    @customer = Customer.find(params[:customer_id])
  end

  def set_visit_history
    @visit_history = @customer.visit_histories.find(params[:id])
  end

  def visit_history_params
    params.require(:visit_history).permit(:visited_user_id, :visited_at, :memo, :next_visit_at)
  end
end

app/controllers/home/visit_histories_controller.rb
# 訪問履歴

class Home::VisitHistoriesController < Home::AuthorizedController

  before_action :set_customer
  before_action :set_visit_history, only: [:edit, :update, :destroy]

  before_action do
    add_breadcrumb '担当顧客管理', home_customers_path
    add_breadcrumb @customer.name, home_customer_path(@customer)
  end

  def new
    add_breadcrumb '新規訪問履歴'
    @visit_history = VisitHistory.new
  end

  def edit
    add_breadcrumb '更新'
  end

  def create
    add_breadcrumb '新規訪問履歴'
    @visit_history = @customer.visit_histories.new(visit_history_params)

    @visit_history.visited_employee = current_employee

    if @visit_history.save
      redirect_to home_customer_path(@customer)
    else
      render :new
    end
  end

  def update
    add_breadcrumb '更新'
    @visit_history.assign_attributes(visit_history_params)

    if @visit_history.save
      redirect_to home_customer_path(@customer), notice: '訪問概要を更新しました。'
    else
      render :edit
    end
  end

  def destroy
    @visit_history.destroy
    redirect_to home_visit_histories_url, notice: '削除しました。'
  end

  private

  def set_customer
    @customer = current_employee.customers.find(params[:customer_id])
  end

  def set_visit_history
    @visit_history = @customer.visit_histories.find(params[:id])
  end

  def visit_history_params
    params.require(:visit_history).permit(:visited_employee_id, :visited_at, :memo, :next_visit_at)
  end
end

app/controllers/visit_histories_controller.rb
class VisitHistoriesController < AuthorizedController

  before_action :set_customer
  before_action :set_visit_history, only: [:edit, :update, :destroy]

  def new
    @visit_history = VisitHistory.new
  end

  def edit
  end

  def create
    @visit_history = @customer.visit_histories.new(visit_history_params)

    @visit_history.visited_employee = current_employee

    if @visit_history.save
      redirect_to customer_path(@customer)
    else
      render :new
    end
  end

  def update

    @visit_history.assign_attributes(visit_history_params)

    # if params[:visit_history][:next_schedule].to_i == 0
    #   @visit_history.next_visit_at = nil
    # end

    if @visit_history.save
      redirect_to customer_path(@customer), notice: '訪問概要を更新しました。'
      # redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @visit_history.destroy
    redirect_to visit_histories_url, notice: 'Visit history was successfully destroyed.'
  end

  private

  def set_customer
    @customer = current_employee.customers.find(params[:customer_id])
  end

  def set_visit_history
    @visit_history = @customer.visit_histories.find(params[:id])
  end

  def visit_history_params
    params.require(:visit_history).permit(:visited_user_id, :visited_at, :memo, :next_visit_at)
  end
end

app/views/visit_histories/_form.html.erb
<%= form_for([@customer, @visit_history], html: {class: 'form-horizontal'}) do |f| %>
  <% if @visit_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit_history.errors.count, "error") %> prohibited this visit_history from being saved:</h2>

      <ul>
        <% @visit_history.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :visited_at, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.datetime_select :visited_at %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :next_visit_at, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.datetime_select :next_visit_at, include_blank: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :memo, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :memo, class: 'form-control', rows: 10 %>
    </div>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/visit_histories/new.html.erb
<h1>「<%= @customer.name %>」様の新規訪問履歴</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_visit_histories_path(@customer) %>